
Metrics/LineLength:
  Max: 99

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false